---
title: "iNaturalist"
output: html_document
---

```{r, results = FALSE, echo=TRUE, warning=FALSE}
# packages (https://statsandr.com/blog/an-efficient-way-to-install-and-load-r-packages/)

packages <- c("rinat", "tidyverse", "leaflet", "htmltools")

installed_packages <- packages %in% rownames(installed.packages())

if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
  } else {
  invisible(lapply(packages, library, character.only = TRUE)); rm(packages, installed_packages)
  }


```

### Obter dados e metadados
```{r dados}
lente <- rinat::get_inat_obs_project("lente-ecologica-biodiversidade-do-norte-fluminense-03ec13fb-b9dc-4175-b47e-09dce7fa5848", type = "info", raw = FALSE)

# extrair registros
lente_obs <- rinat::get_inat_obs_project(lente$id, type = "observations")

```
<br></br>

### Mapa de registros
<br></br>

#### Mapa clássico

```{r mapa}
library(tidyverse)

lente_obs %>% 
  ggplot(aes(x = as.numeric(longitude), y = as.numeric(latitude), color = quality_grade)) +
                           # colour = scientific_name)) +
    geom_polygon(data = map_data("world"),
                 aes(x = long, y = lat, group = group),
                 fill = "grey95",
                 color = "gray40",
                 linewidth = 0.1) +
    geom_point(size = 1.2, alpha = 0.6) +
    coord_fixed(xlim = range(as.numeric(lente_obs$longitude), na.rm = TRUE),
                ylim = range(as.numeric(lente_obs$latitude), na.rm = TRUE)) +
    theme_classic() +
    theme(legend.title = element_blank()) +
    labs(x = "Longitude", y = "Latitude")

```
<br></br>

#### Mapa interativo

```{r mapa_interativo}
library(leaflet)

lente_obs %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(~as.numeric(longitude),
             ~as.numeric(latitude),
             label = ~htmltools::htmlEscape(paste("species=", species_guess, "/", "id=", id)),
             popup = ~htmltools::htmlEscape(paste("data=", observed_on)))

```
<br></br>

### Registros
<br></br>

#### Variacao temporal de registros
```{r}
lente_obs %>% 
  select(observed_on, quality_grade, species_guess, user_id, quality_grade) %>% 
  mutate(ano_mes = as.POSIXct(observed_on) %>% zoo::as.yearmon()) %>% 
  group_by(ano_mes, quality_grade) %>% 
  summarise(occ = n_distinct(species_guess)) %>% 
  ggplot(aes(x = ano_mes, y = occ, fill = quality_grade)) +
    geom_bar(stat = "identity") +
    theme_classic() +
    labs(x = "", y = "registros (n)")
```
<br></br>

#### Registros por usuario
```{r}

# ordenar
ordem <- lente_obs %>% 
  select(observed_on, quality_grade, species_guess, user_id, quality_grade) %>% 
  mutate(ano_mes = as.POSIXct(observed_on) %>% zoo::as.yearmon()) %>% 
  group_by(user_id) %>% 
  summarise(occ = n_distinct(species_guess)) %>%
  arrange(-occ) %>% pull(user_id)

# grafico
lente_obs %>% 
  select(observed_on, quality_grade, species_guess, user_id, quality_grade) %>% 
  mutate(ano_mes = as.POSIXct(observed_on) %>% zoo::as.yearmon()) %>% 
  group_by(user_id, quality_grade) %>% 
  summarise(occ = n_distinct(species_guess)) %>%
  arrange(-occ) %>% 
  ggplot(aes(y = occ, x = factor(user_id, levels = ordem), fill = quality_grade)) +
    geom_bar(stat = "identity") +
    theme_classic() +
    theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5),
          legend.title = element_blank()) +
    labs(x = "", y = "registros (n)")
```
